### ISSUE TITLE
NextAuth doesn't support proxies

### ISSUE THREAD

**Issue by ajhenry** [github-community-projects/private-mirrors#116]
### Describe the bug

NextAuth doesn't support proxies but we need to allow that for corporate firewall bypasses. 

### To Reproduce

More information about the issue can be found here: https://github.com/nextauthjs/next-auth/discussions/3944

### Expected behavior

You should be able to configure a proxy for this

**Comment by sutterj** [comment]
Is this ready to be closed?

**Comment by ajhenry** [comment]
Sure is! We fixed this with #134
