### ISSUE TITLE
Determine level of effort and steps for GitHub-hosted ICF

### ISSUE THREAD

**Issue by ahpook** [github-community-projects/private-mirrors#122]
### Is your feature request related to a problem?

Currently users must self-host the app. While some users prefer (and indeed, some _require_ it), it does present a higher barrier to entry - especially for people just wanting to test pilot the app.

### Describe the solution you'd like

If we can host the app on GitHub infrastructure, users could get a greatly simplified install experience where they can pick it from the Marketplace and both install into their org as well as get an instance up and running without having to wrangle any infrastructure themselves.

This would incur some cost for GitHub, and maybe ought not be published/public on the marketplace for absolutely anyone, but as steps on the path we should determine what it would take to get a "no hosting required" app experience going.

**Comment by ahpook** [comment]
We decided not to pursue this approach - the project will remain an open source, self-hosted solution.

**Comment by MohitDubeyGitHub** [comment]
We want to use this App across multiple GHEC Instances . So Public Mirrors in GHEC Instance 1 & Private Mirrors in GHEC instance 2 because our GHEC 2 is not allowed to have Public Orgs. Is there a way to accomplish this ?

**Comment by cperkulator** [comment]
A hosted option would definitely be nice, especially to test pilot the app. Getting our IT to host new apps isn't the easiest thing in the world.
