### ISSUE TITLE
Rename to "Private Mirrors App"

### ISSUE THREAD

**Issue by ahpook** [github-community-projects/private-mirrors#197]
### Is your feature request related to a problem?

As part of moving to a hosted app and wider beta, we want to rename ICF to "Private Mirrors App". This meets the design goals of concision, disambiguation vs a built-in GitHub feature, and consistency with its actual functionality.

### Describe the solution you'd like

Usage guidance:

* whenever it's fully written out for the first time in text it should be called "Private Mirrors App"
* after the first usage it can be abbreviated "PMA" (s/ICF/PMA/g)
* inside of the product, text strings can use the terminology "Private Mirrors" to refer to the app itself (e.g. page title elements, headers)
* if it's clear from context, docs can use "the app" or "PMA" interchangably
* the repo can be named 'private-mirrors'
* the hostname can be 'private-mirrors.githubapp.com'
* internal code references can use "private mirrors" in snake/camel/whatever case since the "app" part is obvious

**Comment by sutterj** [comment]
@ahpook Did you start working on this?
