### ISSUE TITLE
Add better organization/repository settings

### ISSUE THREAD

**Issue by ajhenry** [github-community-projects/private-mirrors#74]
## Summary

We need a way to configure default settings for users of ICF. Taking this issue as an example: https://github.com/github-community-projects/internal-contribution-forks/issues/71

We should use something like https://github.com/github/safe-settings for managing the input and behavior of these settings. 

## Team

| Role & Responsibility | Username |
|--|--|
| DRI | @ajhenry |
| Engineering | @sutterj |

## Corresponding Work

- [ ] Investigate `github/safe-settings` and see what it would take to integrate
- [ ] Investigate other alternatives to safe-settings 
- [ ] Add sensible defaults for the settings
- [ ] Add documentation for setting up settings

## Supporting Documentation

https://github.com/github/safe-settings

https://github.com/apps/settings

**Comment by ajhenry** [comment]
After chatting with `@decyjphr` on the github/safe-settings project. He informed us the data format they use maps nearly one-to-one with the github REST inputs API and we should expose that format to users to set the defaults for a repo. 

We are going to make the config file part of the deployment of the app. Users can then use safe-settings alongside icf if they want additional protections in their organization.

**Comment by ahpook** [comment]
Gonna close this one out, I think we focused on just disabling actions and left safe-settings out of the picture to avoid scope creep.
