### ISSUE TITLE
Fallback to branch protections when rulesets unavailable

### ISSUE THREAD

**Issue by ajhenry** [github-community-projects/private-mirrors#90]
### Describe the bug

There's currently a known issue where EMU integrations are not allowed to create repository rulesets. We need to fallback to using branch protections until this issue is resolved. 

### To Reproduce

When making rulesets in an EMU org, you will be met with the following error: 

```
{"data":{"createRepositoryRuleset":null},"errors":[{"type":"FORBIDDEN","path":["createRepositoryRuleset"],"extensions":{"saml_failure":false},"locations":[{"line":1,"column":11}],"message":"Unauthorized: As an Enterprise Managed User, you cannot access this content"}]}
```

### Expected behavior

We need to use the old behavior of branch protections when this error occurs

**Comment by sutterj** [comment]
Is this ready to be closed?

**Comment by ahpook** [comment]
This is done, I think!
